image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

pages:
  script:
    - which python
    - python --version
    - which pip
    - pip --version
    - pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints numpydoc
    - pip install -r requirements.txt
    - pip install -e . -vvv
    - which sphinx-build
    - sphinx-build --version
    - sphinx-build -b html ducks/ public/

  artifacts:
    paths:
    - public

  rules:
   - when: manual