image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

pages:
  script:
    - pip install sphinx sphinx-rtd-theme sphinx-autodoc-typehints numpydoc
    - pip install -r requirements.txt
    - pip install -e . -vvv
    - cd ducks ; make html
    - mv _build/html/ ../public/

  artifacts:
    paths:
    - public

  rules:
   - when: manual